### ISSUE TITLE
tokio codec and pins monitring

### ISSUE THREAD

**Issue by anton-dutov** [de-vri-es/serial2-tokio-rs#11]
In my project i need to monitor cts/dsr pins and should have exchange with device by complex protocol. So i use tokio-codec, but it's takes ownership of port itself and i can't read pin states. is it possible to separate control flow and data flow?  To allow me use codec on data flow, and reading pin states on control flow.

Something like that
    
    let port = SerialPort::open(com_port, BAUD_RATE)?;
    let (ctl, pipe) = port.slit_flow();

    ctl.set_dtr(true)?;

    let (mut pipe_tx, mut pipe_rx) = Framed::new(pipe, Codec).split();

**Comment by de-vri-es** [comment]
Hey!

I think you have two options:

1. Migrate to [`tokio_util::codec`](https://docs.rs/tokio-util/latest/tokio_util/codec/index.html) as recommended by `tokio_codec`. Then you can use [`get_ref()`](https://docs.rs/tokio-util/latest/tokio_util/codec/struct.Framed.html#method.get_ref) or [`get_mut()`](https://docs.rs/tokio-util/latest/tokio_util/codec/struct.Framed.html#method.get_mut).

2. If you can not migrate for some reason, you could use [`try_clone()`](https://docs.rs/serial2-tokio/latest/serial2_tokio/struct.SerialPort.html#method.try_clone) before wrapping the serial port. Be sure not to perform reads or writes with the cloned serial port though, since it will interfere with `tokio-codec`.

:)

**Comment by anton-dutov** [comment]
Thank you, it looks like what I need.
